// Cross-language contract test: the Go backend (apps/api) SIGNS an entitlement; this is the BROWSER
// code that must VERIFY it. We load the committed fixture (generated by `go run ./tools/fixturegen`)
// and verify it with the exact WebCrypto Ed25519 path the app uses. If either side's byte encoding
// drifts, this breaks — which is the point. (Node's WebCrypto supports Ed25519 raw import, so this
// runs under Vitest's default node environment.)

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { entitlementValid, verifyEntitlementToken } from './license';

// Mint Ed25519 tokens in-process (the same byte format the Go server emits) so we can exercise the
// stateful gate paths (currentEntitlement / isProUnlocked) without the backend.
async function makeSigner() {
  const kp = (await crypto.subtle.generateKey({ name: 'Ed25519' }, true, ['sign', 'verify'])) as CryptoKeyPair;
  const rawPub = new Uint8Array(await crypto.subtle.exportKey('raw', kp.publicKey));
  const b64url = (b: Uint8Array) => Buffer.from(b).toString('base64url');
  async function sign(claims: Record<string, unknown>): Promise<string> {
    const msg = b64url(new TextEncoder().encode(JSON.stringify(claims)));
    const sig = new Uint8Array(await crypto.subtle.sign({ name: 'Ed25519' }, kp.privateKey, new TextEncoder().encode(msg)));
    return `${msg}.${b64url(sig)}`;
  }
  return { pubB64: Buffer.from(rawPub).toString('base64'), sign };
}

function installLocalStorage(): Map<string, string> {
  const m = new Map<string, string>();
  (globalThis as unknown as { localStorage: Storage }).localStorage = {
    getItem: (k: string) => (m.has(k) ? (m.get(k) as string) : null),
    setItem: (k: string, v: string) => void m.set(k, v),
    removeItem: (k: string) => void m.delete(k),
    clear: () => m.clear(),
    key: () => null,
    length: 0,
  } as Storage;
  return m;
}

interface Fixture {
  publicKeyBase64: string;
  token: string;
  claims: { v: number; lic: string; dev: string; plan: string; iat: number; exp: number };
}

function loadFixture(): Fixture {
  const path = fileURLToPath(new URL('../../../../fixtures/license/entitlement-fixture.json', import.meta.url));
  return JSON.parse(readFileSync(path, 'utf8')) as Fixture;
}

describe('entitlement cross-language verification', () => {
  const fx = loadFixture();

  it('verifies a Go-signed token with the embedded ed25519 public key', async () => {
    const ent = await verifyEntitlementToken(fx.token, fx.publicKeyBase64);
    expect(ent).not.toBeNull();
    expect(ent).toEqual(fx.claims);
  });

  it('rejects a tampered payload', async () => {
    const dot = fx.token.indexOf('.');
    const flipped = (fx.token[0] === 'e' ? 'f' : 'e') + fx.token.slice(1);
    expect(await verifyEntitlementToken(flipped, fx.publicKeyBase64)).toBeNull();
    // a truncated signature segment must also fail
    expect(await verifyEntitlementToken(fx.token.slice(0, dot + 5), fx.publicKeyBase64)).toBeNull();
  });

  it('rejects verification under the wrong public key', async () => {
    // a different (but valid 32-byte) key — all 0x02 bytes, base64
    const wrong = Buffer.alloc(32, 2).toString('base64');
    expect(await verifyEntitlementToken(fx.token, wrong)).toBeNull();
  });

  it('treats the fixture as expired relative to now (exp is 2023)', () => {
    expect(entitlementValid(fx.claims, Date.now() / 1000)).toBe(false);
    // …but valid relative to a clock just before its exp
    expect(entitlementValid(fx.claims, fx.claims.exp - 100)).toBe(true);
  });
});

// Gate state machine — uses stubbed env + localStorage and a fresh dynamic import so the module reads
// VITE_PRO_GATE / VITE_LICENSE_PUBKEY at load.
describe('gate: device binding (#6) + offline unlock', () => {
  afterEach(() => {
    vi.unstubAllEnvs();
    vi.resetModules();
  });

  async function loadGate(pubB64: string) {
    vi.stubEnv('VITE_PRO_GATE', 'true');
    vi.stubEnv('VITE_LICENSE_PUBKEY', pubB64);
    vi.resetModules();
    return import('./license');
  }

  it('unlocks for this device but rejects a token minted for another device', async () => {
    const { pubB64, sign } = await makeSigner();
    const store = installLocalStorage();
    store.set('ad.device', 'devA');
    const gate = await loadGate(pubB64);
    const future = Math.floor(Date.now() / 1000) + 3600;

    store.set('ad.entitlement', JSON.stringify({ token: await sign({ v: 1, lic: 'AD-X', dev: 'devA', plan: 'pro', iat: 0, exp: future }), key: 'AD-X' }));
    expect(await gate.isProUnlocked()).toBe(true);

    // a valid signature but for device 'devB' must NOT unlock on devA (closes copy-the-blob sharing)
    store.set('ad.entitlement', JSON.stringify({ token: await sign({ v: 1, lic: 'AD-X', dev: 'devB', plan: 'pro', iat: 0, exp: future }), key: 'AD-X' }));
    expect(await gate.isProUnlocked()).toBe(false);
  });

  it('locks once the token has expired (no offline fail-open)', async () => {
    const { pubB64, sign } = await makeSigner();
    const store = installLocalStorage();
    store.set('ad.device', 'devA');
    const gate = await loadGate(pubB64);
    const past = Math.floor(Date.now() / 1000) - 3600;
    store.set('ad.entitlement', JSON.stringify({ token: await sign({ v: 1, lic: 'AD-X', dev: 'devA', plan: 'pro', iat: 0, exp: past }), key: 'AD-X' }));
    expect(await gate.isProUnlocked()).toBe(false);
  });
});
